#!/bin/bash

[ $UID -eq 0 ] || {
	echo "initial-setup: This script must be run as root."
	exit 1
}

echo "Adding group 'codybot'"
getent group codybot &>/dev/null ||
	groupadd codybot
echo "Adding user 'codybot'"
getent passwd codybot &>/dev/null ||
	useradd -m -s $(which bash) -g codybot codybot
echo "Adding current user to the codybot group"
[ -z "$USER" ] && USER=user
[ "$USER" = "root" ] && USER=user
getent group codybot | grep $USER &>/dev/null ||
	usermod -G codybot $USER
echo "Creating runtime files: cmd.input cmd.output cmd.ret cmd.url dict.output" \
" dict.url log.fifo prog prog.c stats tmp"
touch cmd.input cmd.output cmd.ret cmd.url dict.output dict.url prog prog.c stats
mkfifo log.fifo
mkdir -v tmp
chown -v codybot:codybot cmd.input cmd.output cmd.ret cmd.url dict.output \
  dict.url log.fifo prog prog.c stats tmp
chmod g+w log.fifo tmp
chmod 755 prog
[ -L /home/codybot/codybot ] ||
	ln -sv $(pwd) /home/codybot/codybot

